version: '3.3'
services:
  api:
    container_name: 'api'
    build: './server'
    volumes:
      - './server:/app'
    restart: 'always'
    depends_on:
      - 'nginx'
  nginx:
    container_name: 'web-server'
    restart: 'always'
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - './webserver:/etc/nginx/conf.d:ro'
    depends_on:
      - 'postgres'
  postgres:
    container_name: 'db'
    restart: 'always'
    image: 'postgres:latest'
    ports:
      - '5431:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
volumes:
  db-data:
    driver: 'local'