version: '3.3'
services:
  nginx:
    container_name: 'web-server'
    restart: 'always'
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - '.server/:/etc/nginx/conf.d:ro'
    depends_on:
      - 'postgres'
  postgres:
    container_name: 'db'
    restart: 'always'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
volumes:
  db-data:
    driver: 'local'